spring:
  application:
    name: taskon-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    csrf:
      enabled: false
    oauth2-redirect-url: "/swagger-ui/oauth2-redirect.html"

jwt:
  secret: ${JWT_SECRET:local_dev_secret}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:1800000}
  refresh-token-validity-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS:1209600000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
