spring:
  application:
    name: taskon-server
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    csrf:
      enabled: false
    oauth2-redirect-url: "/swagger-ui/oauth2-redirect.html"

jwt:
  secret: ${JWT_SECRET:local_dev_secret}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:1800000}
  refresh-token-validity-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS:1209600000}

frontend:
  url: http://localhost:3000,https://taskon.co.kr,https://www.taskon.co.kr

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
